version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXX
    volumes:
      - ./mariadb:/var/lib/mysql
  wordpress:
    image: wordpress
    ports:
      - 3002:80
    environment:
      WORDPRESS_DB_PASSWORD: XXXXXX
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_HOST: mariadb
    volumes:
      - ./www:/var/www/html
